# Welcome to Numpy Tutorial


In [1]:
import numpy as np

In [2]:
# conversion of list to numpy Array
Myarr = np.array([[1,2,3,4,5,6]],np.int32)

In [3]:
Myarr

array([[1, 2, 3, 4, 5, 6]], dtype=int32)

In [4]:
Myarr[0,1]

np.int32(2)

In [5]:
Myarr.shape

(1, 6)

In [6]:
Myarr.dtype

dtype('int32')

In [7]:
# Changing the elements from postion or inserting new element
Myarr[0,1]=9

In [8]:
Myarr

array([[1, 9, 3, 4, 5, 6]], dtype=int32)

**Array Creation : Conversion From othe Python Structures**

In [9]:
Listarray=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [10]:
Listarray

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
Listarray.dtype

dtype('int64')

In [12]:
Listarray.shape

(3, 3)

In [13]:
Listarray.size

9

In [14]:
np.array({22,24,35})

array({24, 35, 22}, dtype=object)

Array Creation : Intrinsic numpy array creation objects(ex.arange,ones,zero etc)

In [15]:
# Use Of Zeros 
Zeros = np.zeros((2,5))

In [16]:
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
Zeros.shape

(2, 5)

In [18]:
Zeros.dtype

dtype('float64')

In [19]:
# Use Of arange
rng = np.arange(17)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [21]:
# Use Of linspace(linear space)
lspace = np.linspace(1,5,12) #>>>>(start,end,no of parts)


In [22]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
# Use Of empty

emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.67293691e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        2.13621350e-306, 6.23053954e-307, 8.91253127e-313]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
# Use Of Identity()
ide = np.identity(43)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(43, 43))

In [29]:
ide.shape

(43, 43)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
# Use Of Reshape
arr.reshape(3,33) #(no. of parts,ele. in each part)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
# By using ravel() we can make above modified data as is is.
arr = arr.ravel()

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.shape

(99,)

**Numpy Axis**

In [36]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [37]:
ar = np.array(x)

In [38]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
ar.sum(axis=0)

array([12,  8,  9])

In [40]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [41]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [42]:
ar.flat

In [43]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [44]:
ar.ndim # ndim stands for number of dimenssions

2

In [45]:
ar.nbytes #( total number of bytes are consumed)

72

In [46]:
# Use Of argmax()
one = np.array([1,4,56,78,6])

In [47]:
one

array([ 1,  4, 56, 78,  6])

In [48]:
one.argmax()  # It Returns the index of largest element

np.int64(3)

In [49]:
one.argmin() # I t Return the index of smallest element

np.int64(0)

In [50]:
one.argsort()  # It Gives the index of elements in sorted order

array([0, 1, 4, 2, 3])

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.argmin()

np.int64(8)

In [53]:
ar.argmax()

np.int64(6)

In [54]:
ar.argmax(axis=0)     # It returns the indexes

array([2, 1, 1])

In [55]:
ar.argmax(axis=1) 

array([2, 2, 0])

In [56]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [57]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [59]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

**Mathematical operations using numpy**

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [62]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [63]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [64]:
np.sqrt(ar)   # square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [65]:
ar.sum()

np.int64(29)

In [66]:
ar.max()

np.int64(7)

In [67]:
ar.min()

np.int64(0)

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [70]:
np.count_nonzero(ar)

8

to prove that numpy uses less space than python(list)

In [71]:
import sys

In [72]:
py_ar = [0,4,55,2]

In [73]:
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1) * len(py_ar)

112

In [75]:
np_ar.itemsize*np_ar.size

32